language: node_js
node_js:
  - "0.10"
before_install:
  - curl https://install.meteor.com | /bin/sh

before_script:
  - npm install -g phantomjs
  - export PHANTOM_PATH=`which phantomjs`


script:
  - meteor --settings settings.json --test --once
